#! /bin/sh
xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal &
pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet & feh --bg-fill ~/Pictures/bg.jpg
$HOME/.config/polybar/launch.sh &
picom --config ~/.config/bspwm/picom.conf &
#keyboard
setxkbmap -option grp:alt_shift_toggle us,ir &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]];
then
	bspc monitor HDMI-1 -d 5 6 7 8
fi

bspc monitor eDP-1 
bspc config border_width        2
bspc config window_gap         10 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
